### ISSUE TITLE
Coopybook has no parse String

### ISSUE THREAD

**Issue by oscaratnc** [zalmane/copybook#1]
Hello  

I was trying to use your module but when I imported it, it threw an error with the following: 
AttributeError: partially initialized 
module 'copybook' has no attribute 'parse_string' (most likely due to a circular import)

do you have that error as well?

**Comment by zalmane** [comment]
how did you import? can you share a snippet?

**Comment by oscaratnc** [comment]
sorry I made a basic mistake  woks fine! :)

**Comment by zalmane** [comment]
Happy to hear! Would appreciate a 'star' to get some exposure. Let me know if you miss any functionality.
