### ISSUE TITLE
PIC by line and column

### ISSUE THREAD

**Issue by Ixiodor** [zalmane/copybook#10]
I'm facing some copybook like that:
```
02 LINE 1 COL 2 AMOUNT PIC X(2).
03 LINE 8 COL 62 PIC XX FROM TT-ALIAS.
```
etc

And that means that PIC starts from LINE (number), COL (number). So you know from where take the data. And it's not all.

I have that too:
```
02 LINE 9 COL 13.
         02 G-001.
          03 OCCURS 3.
           04 UNDERLINE PIC X(14) FROM WM-ALIAS-1.
           04 COL + 1 UNDERLINE PIC X(4) FROM WM-ALIAS-2.
```
That means that from father, you have to move as offset. FATHER_LINE+ SON_LINE .

Found nothing in English but you can watch some examplere here:
https://claudiomaccherani.altervista.org/web_dispense/File/PrgClaCbl.pdf (Italian)

**Comment by zalmane** [comment]
In the first example, what happens between LINE 1 COL 2 and LINE 8 COL 62? Is it just skipped? Is it recurring or just describes one specific instance in that file? 
Please share some more detail and I can look into it. First time I see it.

**Comment by zalmane** [comment]
Sorry for the delay. I won't have time to add this new functionality any time soon. You are welcome to send a PR if you want to tackle it!
