### ISSUE TITLE
Implied and explicit decimal not recognized

### ISSUE THREAD

**Issue by davidpeckham** [zalmane/copybook#15]
The parser doesn't detect **implied_decimal** for a PICTURE clause that uses the V symbol:

       01  WORK-BOOK.
         10  AMOUNT2       PIC -9(4)V99.

or **explicit_decimal**:

       01  WORK-BOOK.
         10  AMOUNT2       PIC -9(4).99.

Looking at Field class, I see that implied decimal is literally implied and not intended to be captured as an attribute. But I also noticed that Field.explicit_decimal is never set because of paren placement in this rule:

```
numeric_pic = Group(
    ...snip...
    )
    + Optional(
        (
            ("V"+FollowedBy("9")("implied_decimal"))
            | ("."+FollowedBy("9")("explicit_decimal"))
        )
    ...snip...
```

We can resolve this by moving the right-most parens:

```
numeric_pic = Group(
    ...snip...
    )
    + Optional(
        (
            ("V"+FollowedBy("9"))("implied_decimal")
            | ("."+FollowedBy("9"))("explicit_decimal")
        )
    ...snip...
```

**Comment by zalmane** [comment]
looks good to me. please resolve the conflict in the PR and we can merge.
