### ISSUE TITLE
wrong method on parser.py - should be oneOf instead of one_of

### ISSUE THREAD

**Issue by cyrultech** [zalmane/copybook#20]

**Comment by davidpeckham** [comment]
@cyrultech, PyParsing aliases one_of as oneOf to remain compatible with pre-PEP8 versions of the library. See [pyparsing/helpers.py](https://github.com/pyparsing/pyparsing/blob/master/pyparsing/helpers.py):

```
@replaced_by_pep8(one_of)
def oneOf(): ...
```
