### ISSUE TITLE
Can't parse 'extended' PIC format

### ISSUE THREAD

**Issue by Ixiodor** [zalmane/copybook#4]
Hi, for example:
```
text = """
       01  WORK-BOOK.
        10 TAX-RATE PIC S9(13)V9(2) SIGN LEADING SEPARATE.
        10  AMOUNT        PIC X(2).
        10  AMOUNT2       PIC S9(4)V9(2).
"""
```
gets parsed but:
```
text = """
       01  WORK-BOOK.
        10 TAX-RATE PIC S9(13)V9(2) SIGN LEADING SEPARATE.
        10  AMOUNT        PIC XX.
        10  AMOUNT2       PIC S9(4)V9(2).
"""
```
results:
Traceback (most recent call last):
  File "XX\pyparsing\core.py", line 1134, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found '10'  (at char 90), (line:4, col:9)

**Comment by zalmane** [comment]
X(2) should be supported. Can you post the full copybook snippet?
Regarding XX it is not supported. Will add.

**Comment by Ixiodor** [comment]
X(2) is parsed correctly in first message.
What goes wrong is:
` 02 LINE 1 COL 2 AMOUNT PIC X(2).`

**Comment by zalmane** [comment]
> 02 LINE 1 COL 2 AMOUNT PIC X(2).
This format is new to me. Can you open a new issue and elaborate what is the "LINE 1 COL 2" clause?

**Comment by zalmane** [comment]
Can this be closed?

**Comment by Ixiodor** [comment]
> > 02 LINE 1 COL 2 AMOUNT PIC X(2).
> > This format is new to me. Can you open a new issue and elaborate what is the "LINE 1 COL 2" clause?

Didn't readed that. I'll close that and open a new one. Thanks.
